/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/Partials/AppFooter.vue')['default']
    AppNav: typeof import('./src/components/Partials/AppNav.vue')['default']
    Button: typeof import('./src/components/Button/index.vue')['default']
    Carousel: typeof import('./src/components/Carousel/index.vue')['default']
    IconCart: typeof import('./src/components/Icons/IconCart.vue')['default']
    IconClose: typeof import('./src/components/Icons/IconClose.vue')['default']
    IconDropdown: typeof import('./src/components/Icons/IconDropdown.vue')['default']
    IconSearch: typeof import('./src/components/Icons/IconSearch.vue')['default']
    IconSpinner: typeof import('./src/components/Icons/IconSpinner.vue')['default']
    Modal: typeof import('./src/components/Modal/index.vue')['default']
    ProductCard: typeof import('./src/components/ProductCard/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextInput: typeof import('./src/components/TextInput/index.vue')['default']
  }
}
