/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/Partials/AppFooter.vue')['default']
    AppNav: typeof import('./src/components/Partials/AppNav.vue')['default']
    Button: typeof import('./src/components/Button/index.vue')['default']
    Carousel: typeof import('./src/components/Carousel/index.vue')['default']
    CartRemove: typeof import('./src/components/Button/CartRemove.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    IconCart: typeof import('./src/components/Icons/IconCart.vue')['default']
    IconClose: typeof import('./src/components/Icons/IconClose.vue')['default']
    IconDropdown: typeof import('./src/components/Icons/IconDropdown.vue')['default']
    IconInfo: typeof import('./src/components/Icons/IconInfo.vue')['default']
    IconPaymentMode: typeof import('./src/components/Icons/IconPaymentMode.vue')['default']
    IconSearch: typeof import('./src/components/Icons/IconSearch.vue')['default']
    IconSpinner: typeof import('./src/components/Icons/IconSpinner.vue')['default']
    Modal: typeof import('./src/components/Modal/index.vue')['default']
    Pill: typeof import('./src/components/Pill.vue')['default']
    ProductCard: typeof import('./src/components/ProductCard/index.vue')['default']
    Remove: typeof import('./src/components/Button/Remove.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Table: typeof import('./src/components/Table/index.vue')['default']
    TextInput: typeof import('./src/components/TextInput/index.vue')['default']
  }
}
